name: leadstudy
description: A study plan app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod:
  state_notifier:
  supabase_flutter: 
  cupertino_icons: 
  freezed_annotation: 
  flutter_dotenv: 
  image_picker: 
  cached_network_image: 
  intl: 
  fl_chart: 
  tuple: 
  percent_indicator: 
  flutter_launcher_icons: ^0.13.1
  awesome_dialog: ^3.0.2
  collection: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  json_serializable:
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - .env
  
  fonts:
  - family: LINESeedJP
    fonts:
      - asset: assets/fonts/LINESeedJP_A_OTF_Th.otf
        weight: 100
      - asset: assets/fonts/LINESeedJP_A_OTF_Rg.otf
        weight: 400
      - asset: assets/fonts/LINESeedJP_A_OTF_Bd.otf
        weight: 700
      - asset: assets/fonts/LINESeedJP_A_OTF_Eb.otf
        weight: 800

flutter_icons:
   android: false
   ios: true
   image_path: 'assets/images/icon.png'
   remove_alpha_ios: true